version: '3.8'

services:
  ai-detection:
    build: .
    ports:
      - \"3001:3001\"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-production-jwt-secret
      - SESSION_SECRET=your-production-session-secret
    volumes:
      - ./data:/app/data
      - ./temp:/app/temp
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - \"80:80\"
      - \"443:443\"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - ai-detection
    restart: unless-stopped